# Generated by Django 5.2.6 on 2025-09-26 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('conference_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('theme', models.CharField(choices=[('CS', 'Computer Science'), ('AI', 'Artificial Intelligence'), ('SE', 'Science & Engineering'), ('SSE', 'Social Sciences & Education'), ('IT', 'Interdisciplinary Themes')], max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('Submission_id', models.CharField(editable=False, max_length=255, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('keyword', models.TextField()),
                ('paper', models.FileField(upload_to='papers/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=50)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
                ('payed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='ConferenceApp.conference')),
            ],
        ),
    ]
